# Import and preprocess of italian Covid-19 dataset

In [1]:
import pandas as pd
import glob
import os

## Goal:

Create regional and national dataset whit information about covid-19 epidemic

## Dataset structure

Structure of dataset are same for national and regional scale, below the explanation of columns: <br>
<ul>
<li><b>total_cases: </b>cumulative number of infect<br></li>
<li><b>daily_cases: </b>daily new infect<br></li>
<li><b>actual_cases: </b>people actually infect<br></li>
<li><b>total_healed: </b>cumulative number of healed<br></li>
<li><b>daily_healed: </b>daily number of healed<br></li>
<li><b>total_dead: </b>cumulative number of dead<br></li>
<li><b>daily_dead: </b>daily number of dead<br></li>
<li><b>total_home_isolation: </b>cumulative number of people forced to home isolation<br></li>
<li><b>daily_home_isolation: </b>daily number of people forced to home isolation, variation between day before, can be negative<br></li>
<li><b>total_recovered_with_symptoms: </b>cumulative number of people recovered with symptoms<br></li>
<li><b>daily_recovered_with_symptoms: </b>daily number of people recovered with symptoms, variation between day before, can be negative<br></li>
<li><b>total_intensive_care: </b>cumulative number of people in intesive care<br></li>
<li><b>daily_intensive_care: </b>daily number of people in intesive care, variation between day before, can be negative<br></li>
<li><b>total_hospitalized: </b>cumulative number of hospitalized: simple recover + intensive care<br></li>
<li><b>daily_hospitalized: </b>daily number of hospitalized: simple recover + intensive care, variation between day before, can be negative<br></li>
<li><b>total_test: </b>cumulative number of test made<br></li>
<li><b>daily_test: </b>daily number of test made<br></li>
</ul>

In [2]:
#define colums of final dataset
dtregions_cols = ["total_cases","daily_cases","actual_cases","total_healed","daily_healed","total_dead","daily_dead",
                  "total_home_isolation","daily_home_isolation","total_recovered_with_symptoms","daily_recovered_with_symptoms",
                  "total_intensive_care","daily_intensive_care","total_hospitalized","daily_hospitalized","total_test","daily_test"]

#get path for os
path = os.getcwd() + "/data_source/Italia/COVID-19-master/dati-regioni/"
path = path.replace("/",os.path.sep)

dailycsv = glob.glob(path + "*.csv")

dailycsv.remove(path + "dpc-covid19-ita-regioni.csv")
dailycsv.remove(path + "dpc-covid19-ita-regioni-latest.csv")

#define container for dataset
dtregions_ita_array = {}

In [3]:
#read all daily CSV then put into dataset divided by region
for file in dailycsv:
    dtregions_ita = pd.read_csv(file, index_col = 0)
    for region in dtregions_ita["denominazione_regione"].values:
        try:
            dtregions_ita_array[region] = dtregions_ita_array[region].append(dtregions_ita.loc[dtregions_ita["denominazione_regione"] == region], sort=True)
        except:
            dtregions_ita_array[region] = dtregions_ita.loc[dtregions_ita["denominazione_regione"] == region]
        dtregions_ita_array[region].drop(['stato', 'codice_regione', 'denominazione_regione', 'lat', 'long', "note_en", "note_it"], axis = 1, inplace = True)

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [4]:
dtregions_ita_array["Abruzzo"]

,casi_testati,deceduti,dimessi_guariti,isolamento_domiciliare,nuovi_positivi,ricoverati_con_sintomi,tamponi,terapia_intensiva,totale_casi,totale_ospedalizzati,totale_positivi,variazione_totale_positivi
data,,,,,,,,,,,,
2020-03-06T17:00:00,NaN,0,0,0,1,9,96,0,9,9,9,1
2020-03-12T17:00:00,NaN,2,4,19,46,47,867,12,84,59,78,41
2020-03-13T17:00:00,NaN,2,4,27,5,42,958,14,89,56,83,5
2020-03-07T18:00:00,NaN,0,0,0,2,11,123,0,11,11,11,2
2020-03-11T17:00:00,NaN,1,0,11,0,17,310,9,38,26,37,0
2020-03-05T17:00:00,NaN,0,0,0,1,8,96,0,8,8,8,1
2020-03-04T17:00:00,NaN,0,0,0,1,7,85,0,7,7,7,1
2020-03-10T18:00:00,NaN,1,0,11,8,17,310,9,38,26,37,7
2020-03-14T17:00:00,NaN,2,4,41,23,51,1232,14,112,65,106,23
2020-03-28T17:00:00,NaN,76,30,646,116,311,7003,70,1133,381,1027,102
2020-03-29T17:00:00,NaN,88,36,772,160,329,7730,68,1293,397,1169,142
2020-03-01T17:00:00,NaN,0,0,2,3,3,52,0,5,3,5,3
2020-03-15T17:00:00,NaN,3,6,28,25,72,1419,28,137,100,128,22
2020-03-03T18:00:00,NaN,0,0,1,1,5,52,0,6,5,6,1
2020-03-17T17:00:00,NaN,6,7,90,53,94,1688,32,229,126,216,51
2020-03-16T17:00:00,NaN,4,7,57,39,71,1533,37,176,108,165,37
2020-03-02T18:00:00,NaN,0,0,2,0,3,52,0,5,3,5,0
2020-04-03T17:00:00,NaN,146,116,864,66,361,11890,76,1563,437,1301,50
2020-04-17T17:00:00,NaN,246,255,1580,97,319,25436,43,2443,362,1942,92
2020-04-16T17:00:00,NaN,243,253,1484,72,324,23786,42,2346,366,1850,40
2020-04-02T17:00:00,NaN,133,113,835,61,341,10647,75,1497,416,1251,40
2020-04-14T17:00:00,NaN,232,213,1403,32,345,20935,52,2245,397,1800,22
2020-04-01T17:00:00,NaN,123,102,798,35,342,9610,71,1436,413,1211,20
2020-04-15T17:00:00,NaN,240,224,1425,29,341,22500,44,2274,385,1810,10
2020-04-11T17:00:00,NaN,206,190,1355,106,315,19441,54,2120,369,1724,89
2020-04-05T17:00:00,NaN,158,125,1006,75,347,13598,67,1703,414,1420,64
2020-04-04T17:00:00,NaN,153,119,931,65,354,12837,71,1628,425,1356,55
2020-04-10T17:00:00,NaN,198,181,1277,83,305,18088,53,2014,358,1635,69
2020-04-06T17:00:00,NaN,169,127,1019,18,340,14198,66,1721,406,1425,5
2020-04-12T17:00:00,NaN,212,206,1342,40,346,20594,54,2160,400,1742,18
2020-02-28T18:00:00,NaN,0,0,0,0,1,33,0,1,1,1,0
2020-02-29T17:00:00,NaN,0,0,0,1,2,43,0,2,2,2,1
2020-04-13T17:00:00,NaN,224,211,1373,53,351,20667,54,2213,405,1778,36
2020-04-07T17:00:00,NaN,172,136,1087,78,337,14904,67,1799,404,1491,66
2020-04-22T17:00:00,24317.0,276,349,1764,66,309,30348,35,2733,344,2108,41
2020-02-24T18:00:00,NaN,0,0,0,0,0,5,0,0,0,0,0
2020-02-25T18:00:00,NaN,0,0,0,0,0,5,0,0,0,0,0
2020-04-23T17:00:00,24751.0,280,405,1747,52,322,31187,31,2785,353,2100,-8
2020-04-09T17:00:00,NaN,194,171,1203,72,306,16847,57,1931,363,1566,32
2020-04-21T17:00:00,23901.0,271,329,1714,55,318,29906,35,2667,353,2067,5
2020-02-27T18:00:00,NaN,0,0,0,1,1,33,0,1,1,1,1
2020-02-26T18:00:00,NaN,0,0,0,0,0,13,0,0,0,0,0
2020-04-20T17:00:00,22552.0,263,287,1704,91,320,27942,38,2612,358,2062,75
2020-04-08T17:00:00,NaN,179,146,1141,60,331,15846,62,1859,393,1534,43
2020-04-18T17:00:00,NaN,253,263,1609,44,321,27016,41,2487,362,1971,29
2020-04-19T17:00:00,22424.0,258,276,1630,34,317,27791,40,2521,357,1987,16
2020-03-27T17:00:00,NaN,68,24,565,71,289,6109,71,1017,360,925,65
2020-03-26T17:00:00,NaN,63,23,516,133,280,5488,64,946,344,860,122
2020-03-18T17:00:00,NaN,7,7,109,34,99,2054,41,263,140,249,33
2020-03-30T17:00:00,NaN,102,74,778,52,322,7948,69,1345,391,1169,0
2020-03-24T17:00:00,NaN,46,21,331,26,234,4294,57,689,291,622,17
2020-03-25T17:00:00,NaN,52,23,431,124,248,4982,59,813,307,738,116
2020-03-31T17:00:00,NaN,115,95,783,56,335,8758,73,1401,408,1191,22
2020-03-19T17:00:00,NaN,11,8,138,122,181,2409,47,385,228,366,117
2020-03-21T17:00:00,NaN,22,13,265,80,185,3035,44,529,229,494,72
2020-03-09T18:00:00,NaN,0,0,5,13,25,237,0,30,25,30,13
2020-03-08T18:00:00,NaN,0,0,3,6,14,163,0,17,14,17,6
2020-03-20T17:00:00,NaN,17,10,184,64,190,2695,48,449,238,422,56
2020-03-22T17:00:00,NaN,33,15,272,58,218,3375,49,587,267,539,45
2020-03-23T17:00:00,NaN,38,20,325,76,228,3674,52,663,280,605,66

In [5]:
#translate some name and sort dataset by date
for region in dtregions_ita_array:
    dtregions_ita_array[region].index.name = "date"
    dtregions_ita_array[region].sort_values(by=['date'], inplace = True)
    dtregions_ita_array[region] = dtregions_ita_array[region].rename({'ricoverati_con_sintomi': 'hospitalized_with_symptoms', 
                                                                      'terapia_intensiva': 'intensive_care', 
                                                                      'totale_ospedalizzati': 'total_hospitalized', 
                                                                      'isolamento_domiciliare': 'home_isolation',
                                                                      'totale_positivi': 'total_actual_positive',
                                                                      'nuovi_positivi': 'new_actual_positive',
                                                                      'dimessi_guariti': 'healed',
                                                                      'deceduti': 'dead',
                                                                      'totale_casi': 'total_cases',
                                                                      'tamponi': 'test',}
                                                                     ,axis='columns')

In [6]:
#create sample datatset
dt_sample = dtregions_ita_array["Lombardia"].copy()[[]]
dt_sample = dt_sample.reindex(columns=dt_sample.columns.tolist() + dtregions_cols)

In [7]:
#define containmer for dataset
dtregions_array = {} 

#create one dataset foreach region and start filling with avaible data
for region in dtregions_ita_array:
    dtregions_array[region] = dt_sample.copy()
    dtregions_array[region].total_cases = dtregions_ita_array[region].total_cases
    dtregions_array[region].total_healed = dtregions_ita_array[region].healed
    dtregions_array[region].total_dead = dtregions_ita_array[region].dead
    dtregions_array[region].total_recovered_with_symptoms = dtregions_ita_array[region].hospitalized_with_symptoms
    dtregions_array[region].total_intensive_care = dtregions_ita_array[region].intensive_care
    dtregions_array[region].total_home_isolation = dtregions_ita_array[region].home_isolation
    dtregions_array[region].total_hospitalized = dtregions_ita_array[region].total_hospitalized
    dtregions_array[region].total_test = dtregions_ita_array[region].test

In [8]:
#calculate the other data 
for region in dtregions_array:
    for i in range(len(dtregions_array[region].index)):
        if i == 0:
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_cases")] = dtregions_array[region].iloc[i].total_cases
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_healed")] = dtregions_array[region].iloc[i].total_healed
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_dead")] = dtregions_array[region].iloc[i].total_dead
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("actual_cases")] = dtregions_array[region].iloc[i].total_cases - dtregions_array[region].iloc[i].total_dead- dtregions_array[region].iloc[i].total_healed
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_home_isolation")] = dtregions_array[region].iloc[i].total_home_isolation
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_recovered_with_symptoms")] = dtregions_array[region].iloc[i].total_recovered_with_symptoms
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_intensive_care")] = dtregions_array[region].iloc[i].total_intensive_care
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_hospitalized")] = dtregions_array[region].iloc[i].total_hospitalized
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_test")] = dtregions_array[region].iloc[i].total_test
        else:
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_cases")] = dtregions_array[region].iloc[i].total_cases - dtregions_array[region].iloc[i-1].total_cases
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_dead")] = dtregions_array[region].iloc[i].total_dead - dtregions_array[region].iloc[i-1].total_dead
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_healed")] = dtregions_array[region].iloc[i].total_healed - dtregions_array[region].iloc[i-1].total_healed
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("actual_cases")] = dtregions_array[region].iloc[i].total_cases - dtregions_array[region].iloc[i].total_dead- dtregions_array[region].iloc[i].total_healed
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_home_isolation")] = dtregions_array[region].iloc[i].total_home_isolation - dtregions_array[region].iloc[i-1].total_home_isolation
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_recovered_with_symptoms")] = dtregions_array[region].iloc[i].total_recovered_with_symptoms - dtregions_array[region].iloc[i-1].total_recovered_with_symptoms
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_intensive_care")] = dtregions_array[region].iloc[i].total_intensive_care - dtregions_array[region].iloc[i-1].total_intensive_care
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_hospitalized")] = dtregions_array[region].iloc[i].total_hospitalized - dtregions_array[region].iloc[i-1].total_hospitalized
            dtregions_array[region].iloc[i, dtregions_array[region].columns.get_loc("daily_test")] = dtregions_array[region].iloc[i].total_test - dtregions_array[region].iloc[i-1].total_test
    dtregions_array[region].loc[:,dtregions_cols] = dtregions_array[region].loc[:,dtregions_cols].astype(int)

Creiamo adesso un Dataframe raggruppando tutte le informazioni di ogni singola regione per singola data

In [9]:
#aggregate regional dataframe to create national data
dtitaly = dt_sample.copy()
dtitaly.fillna(0, inplace=True)

for i in range(len(dtregions_array["Lombardia"])):
    for region in dtregions_array:
        dtitaly.iloc[i] += dtregions_array[region].iloc[i]
        
dtitaly.loc[:,dtitaly.columns] = dtitaly.loc[:,dtitaly.columns].astype(int)

Converting dates from String to Datetime

In [10]:
import datetime as dt

index_list = dtitaly.index.tolist()
for i in range(len(index_list)):
    index_list[i] = dt.datetime.strptime(index_list[i], '%Y-%m-%dT%H:%M:%S').date()

dtitaly.index = index_list
dtitaly.index.name = 'date'

for region in dtregions_array:
    index_list = dtregions_array[region].index.tolist()
    for i in range(len(index_list)):
        index_list[i] = dt.datetime.strptime(index_list[i], '%Y-%m-%dT%H:%M:%S').date()

    dtregions_array[region].index = index_list
    dtregions_array[region].index.name = 'date'

In [16]:
#get path for os
path = os.getcwd() + "/parsed_data/italy/"
path = path.replace("/",os.path.sep)
#save data as CSV 
for region in dtregions_array:
    dtregions_array[region].to_csv (path + region.lower() + ".csv", index = True, header=True)

dtitaly.to_csv (path + "italy.csv", index = True, header=True)