Import data from Brazil

In [1]:
import pandas as pd
import glob
import os

path = os.getcwd() + "/data_source/Brazil/brazil_covid19.csv"
path = path.replace("/",os.path.sep)

columns = ["total_cases","daily_cases","actual_cases","total_dead","daily_dead", "total_test","daily_test"]


dataset = pd.read_csv(path, index_col = 0)
dataset = dataset.fillna(0)
dataset

             hour              state  suspects  refuses  cases  deaths
date
2020-01-30  16:00       Minas Gerais         1        0      0       0
2020-01-30  16:00     Rio de Janeiro         1        0      0       0
2020-01-30  16:00     Santa Catarina         0        2      0       0
2020-01-30  16:00          São Paulo         3        1      0       0
2020-01-30  16:00  Rio Grande do Sul         2        2      0       0
...           ...                ...       ...      ...    ...     ...
2020-03-23      0            Roraima         7       22      2       0
2020-03-23      0     Santa Catarina       410        0     68       0
2020-03-23      0          São Paulo         0        0    745      30
2020-03-23      0            Sergipe         0        0     10       0
2020-03-23      0          Tocantins         0        0      5       0

[819 rows x 6 columns]

In [12]:
#Delate duplicated values with the same index!
dataset = dataset[~dataset.reset_index().duplicated().values]

Grouping by date

In [13]:
dataset = dataset.groupby(["date"]).sum()
dataset

            suspects  refuses  cases  deaths
date
2020-01-30         9        6      0       0
2020-01-31        13        9      0       0
2020-02-01        16       10      0       0
2020-02-02        16       10      0       0
2020-02-03        14       13      0       0
2020-02-04        13       16      0       0
2020-02-05        11       21      0       0
2020-02-06         9       24      0       0
2020-02-07         8       26      0       0
2020-02-08         8       28      0       0
2020-02-09        11       28      0       0
2020-02-10         7       32      0       0
2020-02-11         8       33      0       0
2020-02-12        11       33      0       0
2020-02-13         6       40      0       0
2020-02-14         4       43      0       0
2020-02-15         3       45      0       0
2020-02-16         3       45      0       0
2020-02-17         3       45      0       0
2020-02-18         5       45      0       0
2020-02-19         2       48      0       0
2020-02-20         1       50      0       0
2020-02-21         1       51      0       0
2020-02-22         1       52      0       0
2020-02-23         2       53      0       0
2020-02-24         4       54      0       0
2020-02-25         4       55      0       0
2020-02-26        20       59      1       0
2020-02-27       132       60      1       0
2020-02-28       182       71      1       0
2020-02-29       207       79      2       0
2020-03-01       252       89      2       0
2020-03-02       433      162      2       0
2020-03-03       488      240      2       0
2020-03-04       530      315      3       0
2020-03-05       636      378      7       0
2020-03-06       768      480     13       0
2020-03-07       674      602     19       0
2020-03-08       663      632     25       0
2020-03-10       893      780     34       0
2020-03-11       907      935     52       0
2020-03-12      1422     1163     77       0
2020-03-13      1485     1344     98       0
2020-03-14      1496     1413    121       0
2020-03-15      1913     1486    200       0
2020-03-16      2064     1624    234       0
2020-03-17      8819     1890    291       1
2020-03-18     11278     1841    428       4
2020-03-19     14886     2900    682       7
2020-03-20     17557     3038    931      12
2020-03-21     12947     3943   1173      18
2020-03-22     15436     3446   1565      25
2020-03-23     16643     4924   1919      34

Day 2020-03-09 is missing so we add the date with unchanged values from 2020-03-08

In [14]:
dataset.loc["2020-03-09"] = dataset.loc["2020-03-08"]
dataset.sort_index(inplace=True)
dataset

            suspects  refuses  cases  deaths
date
2020-01-30         9        6      0       0
2020-01-31        13        9      0       0
2020-02-01        16       10      0       0
2020-02-02        16       10      0       0
2020-02-03        14       13      0       0
2020-02-04        13       16      0       0
2020-02-05        11       21      0       0
2020-02-06         9       24      0       0
2020-02-07         8       26      0       0
2020-02-08         8       28      0       0
2020-02-09        11       28      0       0
2020-02-10         7       32      0       0
2020-02-11         8       33      0       0
2020-02-12        11       33      0       0
2020-02-13         6       40      0       0
2020-02-14         4       43      0       0
2020-02-15         3       45      0       0
2020-02-16         3       45      0       0
2020-02-17         3       45      0       0
2020-02-18         5       45      0       0
2020-02-19         2       48      0       0
2020-02-20         1       50      0       0
2020-02-21         1       51      0       0
2020-02-22         1       52      0       0
2020-02-23         2       53      0       0
2020-02-24         4       54      0       0
2020-02-25         4       55      0       0
2020-02-26        20       59      1       0
2020-02-27       132       60      1       0
2020-02-28       182       71      1       0
2020-02-29       207       79      2       0
2020-03-01       252       89      2       0
2020-03-02       433      162      2       0
2020-03-03       488      240      2       0
2020-03-04       530      315      3       0
2020-03-05       636      378      7       0
2020-03-06       768      480     13       0
2020-03-07       674      602     19       0
2020-03-08       663      632     25       0
2020-03-09       663      632     25       0
2020-03-10       893      780     34       0
2020-03-11       907      935     52       0
2020-03-12      1422     1163     77       0
2020-03-13      1485     1344     98       0
2020-03-14      1496     1413    121       0
2020-03-15      1913     1486    200       0
2020-03-16      2064     1624    234       0
2020-03-17      8819     1890    291       1
2020-03-18     11278     1841    428       4
2020-03-19     14886     2900    682       7
2020-03-20     17557     3038    931      12
2020-03-21     12947     3943   1173      18
2020-03-22     15436     3446   1565      25
2020-03-23     16643     4924   1919      34

Creating a new dataframe with our specific format

In [15]:
brazil_dataset = pd.DataFrame().reindex_like(dataset)
brazil_dataset = pd.DataFrame(index = dataset.index , columns = columns) 
brazil_dataset = brazil_dataset.fillna(0)
brazil_dataset

,total_cases,daily_cases,actual_cases,total_dead,daily_dead,total_test,daily_test
date,,,,,,,
2020-01-30,0,0,0,0,0,0,0
2020-01-31,0,0,0,0,0,0,0
2020-02-01,0,0,0,0,0,0,0
2020-02-02,0,0,0,0,0,0,0
2020-02-03,0,0,0,0,0,0,0
2020-02-04,0,0,0,0,0,0,0
2020-02-05,0,0,0,0,0,0,0
2020-02-06,0,0,0,0,0,0,0
2020-02-07,0,0,0,0,0,0,0
2020-02-08,0,0,0,0,0,0,0
2020-02-09,0,0,0,0,0,0,0
2020-02-10,0,0,0,0,0,0,0
2020-02-11,0,0,0,0,0,0,0
2020-02-12,0,0,0,0,0,0,0
2020-02-13,0,0,0,0,0,0,0
2020-02-14,0,0,0,0,0,0,0
2020-02-15,0,0,0,0,0,0,0
2020-02-16,0,0,0,0,0,0,0
2020-02-17,0,0,0,0,0,0,0
2020-02-18,0,0,0,0,0,0,0
2020-02-19,0,0,0,0,0,0,0
2020-02-20,0,0,0,0,0,0,0
2020-02-21,0,0,0,0,0,0,0
2020-02-22,0,0,0,0,0,0,0
2020-02-23,0,0,0,0,0,0,0
2020-02-24,0,0,0,0,0,0,0
2020-02-25,0,0,0,0,0,0,0
2020-02-26,0,0,0,0,0,0,0
2020-02-27,0,0,0,0,0,0,0
2020-02-28,0,0,0,0,0,0,0
2020-02-29,0,0,0,0,0,0,0
2020-03-01,0,0,0,0,0,0,0
2020-03-02,0,0,0,0,0,0,0
2020-03-03,0,0,0,0,0,0,0
2020-03-04,0,0,0,0,0,0,0
2020-03-05,0,0,0,0,0,0,0
2020-03-06,0,0,0,0,0,0,0
2020-03-07,0,0,0,0,0,0,0
2020-03-08,0,0,0,0,0,0,0
2020-03-09,0,0,0,0,0,0,0
2020-03-10,0,0,0,0,0,0,0
2020-03-11,0,0,0,0,0,0,0
2020-03-12,0,0,0,0,0,0,0
2020-03-13,0,0,0,0,0,0,0
2020-03-14,0,0,0,0,0,0,0
2020-03-15,0,0,0,0,0,0,0
2020-03-16,0,0,0,0,0,0,0
2020-03-17,0,0,0,0,0,0,0
2020-03-18,0,0,0,0,0,0,0
2020-03-19,0,0,0,0,0,0,0
2020-03-20,0,0,0,0,0,0,0
2020-03-21,0,0,0,0,0,0,0
2020-03-22,0,0,0,0,0,0,0
2020-03-23,0,0,0,0,0,0,0

Filling the new dataframe with the avaiable data

In [16]:
from datetime import datetime, timedelta

for days in dataset.index:
    try:
        #from 2nd row ---- to subtract a day from the date we had to convert it to a date and then back to a string
        yesterday = (datetime.strptime(days,"%Y-%m-%d")-timedelta(days=1)).strftime("%Y-%m-%d")
        brazil_dataset.loc[days]["daily_cases"] = dataset.loc[days]["cases"]-dataset.loc[yesterday]["cases"]
        brazil_dataset.loc[days]["daily_dead"] = dataset.loc[days]["deaths"] - dataset.loc[yesterday]["deaths"]
        brazil_dataset.loc[days]["daily_test"] = (dataset.loc[days]["suspects"] + dataset.loc[days]["refuses"] + dataset.loc[days]["cases"]) - (dataset.loc[yesterday]["suspects"] + dataset.loc[yesterday]["refuses"] + dataset.loc[yesterday]["cases"])
    except:
        #First row
        brazil_dataset.loc[days]["daily_cases"] = dataset.loc[days]["cases"]
        brazil_dataset.loc[days]["daily_dead"] = dataset.loc[days]["deaths"]
        brazil_dataset.loc[days]["daily_test"] = dataset.loc[days]["suspects"] + dataset.loc[days]["refuses"] + dataset.loc[days]["cases"]
    finally:
        #Single row
        brazil_dataset.loc[days]["total_cases"] = dataset.loc[days]["cases"]
        #Missing recovered -> brazil_dataset.loc[days]["actual_cases"] =
        brazil_dataset.loc[days]["total_dead"] = dataset.loc[days]["deaths"]
        brazil_dataset.loc[days]["total_test"] = dataset.loc[days]["suspects"] + dataset.loc[days]["refuses"] + dataset.loc[days]["cases"]


brazil_dataset

,total_cases,daily_cases,actual_cases,total_dead,daily_dead,total_test,daily_test
date,,,,,,,
2020-01-30,0,0,0,0,0,15,15
2020-01-31,0,0,0,0,0,22,7
2020-02-01,0,0,0,0,0,26,4
2020-02-02,0,0,0,0,0,26,0
2020-02-03,0,0,0,0,0,27,1
2020-02-04,0,0,0,0,0,29,2
2020-02-05,0,0,0,0,0,32,3
2020-02-06,0,0,0,0,0,33,1
2020-02-07,0,0,0,0,0,34,1
2020-02-08,0,0,0,0,0,36,2
2020-02-09,0,0,0,0,0,39,3
2020-02-10,0,0,0,0,0,39,0
2020-02-11,0,0,0,0,0,41,2
2020-02-12,0,0,0,0,0,44,3
2020-02-13,0,0,0,0,0,46,2
2020-02-14,0,0,0,0,0,47,1
2020-02-15,0,0,0,0,0,48,1
2020-02-16,0,0,0,0,0,48,0
2020-02-17,0,0,0,0,0,48,0
2020-02-18,0,0,0,0,0,50,2
2020-02-19,0,0,0,0,0,50,0
2020-02-20,0,0,0,0,0,51,1
2020-02-21,0,0,0,0,0,52,1
2020-02-22,0,0,0,0,0,53,1
2020-02-23,0,0,0,0,0,55,2
2020-02-24,0,0,0,0,0,58,3
2020-02-25,0,0,0,0,0,59,1
2020-02-26,1,1,0,0,0,80,21
2020-02-27,1,0,0,0,0,193,113
2020-02-28,1,0,0,0,0,254,61
2020-02-29,2,1,0,0,0,288,34
2020-03-01,2,0,0,0,0,343,55
2020-03-02,2,0,0,0,0,597,254
2020-03-03,2,0,0,0,0,730,133
2020-03-04,3,1,0,0,0,848,118
2020-03-05,7,4,0,0,0,1021,173
2020-03-06,13,6,0,0,0,1261,240
2020-03-07,19,6,0,0,0,1295,34
2020-03-08,25,6,0,0,0,1320,25
2020-03-09,25,0,0,0,0,1320,0
2020-03-10,34,9,0,0,0,1707,387
2020-03-11,52,18,0,0,0,1894,187
2020-03-12,77,25,0,0,0,2662,768
2020-03-13,98,21,0,0,0,2927,265
2020-03-14,121,23,0,0,0,3030,103
2020-03-15,200,79,0,0,0,3599,569
2020-03-16,234,34,0,0,0,3922,323
2020-03-17,291,57,0,1,1,11000,7078
2020-03-18,428,137,0,4,3,13547,2547
2020-03-19,682,254,0,7,3,18468,4921
2020-03-20,931,249,0,12,5,21526,3058
2020-03-21,1173,242,0,18,6,18063,-3463
2020-03-22,1565,392,0,25,7,20447,2384
2020-03-23,1919,354,0,34,9,23486,3039

Converting dates from String to Datetime

In [17]:
import datetime as dt

index_list = brazil_dataset.index.tolist()

for i in range(len(index_list)):
    index_list[i] = dt.datetime.strptime(index_list[i], '%Y-%m-%d').date()

brazil_dataset.index = index_list
brazil_dataset.index.name = 'date'

Il Database negli ultimi giorni è diventato inconsistente, per esempio in San Paolo il numero di sospetti e negativi diventa 0, nonstante i dati siano comulativi

In [18]:
#save data as CSV 

path = os.getcwd() + "/parsed_data/brazil/"
path = path.replace("/",os.path.sep)

brazil_dataset.to_csv (path + "brazil.csv", index = True, header=True)