Import USA data

In [1]:
import pandas as pd
import glob
import os

#get path for os
path = os.getcwd() + "/data_source/USA/covid-tracking-data-master/data/states_daily_4pm_et.csv"
path = path.replace("/",os.path.sep)

#Data of healed are not present
#Home isolation are positive - hospitalized
#Intensive care and recovered is not present

columns = ["total_cases","daily_cases","actual_cases","total_dead","daily_dead",
                  "total_home_isolation","daily_home_isolation",
                  "total_hospitalized","daily_hospitalized","total_test","daily_test"]


dataset = pd.read_csv(path, index_col = 0)
dataset = dataset.fillna(0)

Grouping by date

In [2]:
dataset = dataset.groupby(["date"]).sum()
dataset

,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,recovered,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
date,,,,,,,,,,,,,,,,,,,,,
20200122,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
20200123,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
20200124,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
20200125,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
20200126,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20200420,773020.0,3231027.0,4037.0,55509.0,82879.0,14691.0,2193.0,5567.0,214.0,54438.0,...,82879.0,4008084.0,4004047.0,4004047.0,1822,1528.0,1998.0,114366.0,23534.0,137900.0
20200421,800305.0,3355282.0,3956.0,58468.0,84292.0,15228.0,2315.0,5514.0,214.0,58117.0,...,84292.0,4159543.0,4155587.0,4155587.0,1822,2674.0,1413.0,124255.0,27285.0,151540.0
20200422,827963.0,3641232.0,4191.0,58173.0,85543.0,15341.0,2370.0,5474.0,227.0,61519.0,...,85543.0,4473386.0,4469195.0,4469195.0,1822,2133.0,1251.0,285950.0,27658.0,313608.0
20200423,859318.0,3800932.0,4258.0,57879.0,91108.0,15163.0,2428.0,5464.0,227.0,63547.0,...,91108.0,4664508.0,4660250.0,4660250.0,1822,1886.0,5601.0,159700.0,31355.0,191055.0
20200424,890816.0,3992986.0,4396.0,56118.0,93107.0,15078.0,2468.0,5187.0,227.0,80958.0,...,93107.0,4888198.0,4883802.0,4883802.0,1822,1772.0,1999.0,192054.0,31498.0,223552.0

Converting dates from String to Datetime

In [3]:
import datetime as dt

index_list = dataset.index.tolist()

for i in range(len(index_list)):
    index_list[i] = dt.datetime.strptime(str(index_list[i]), '%Y%m%d').date()

dataset.index = index_list
dataset.index.name = 'date'

dataset.index[0]

datetime.date(2020, 1, 22)

Creating a new dataframe with our specific format

In [5]:
usa_dataset = pd.DataFrame().reindex_like(dataset)
usa_dataset = pd.DataFrame(index = dataset.index , columns = columns) 
usa_dataset = usa_dataset.fillna(0)
usa_dataset

,total_cases,daily_cases,actual_cases,total_dead,daily_dead,total_home_isolation,daily_home_isolation,total_hospitalized,daily_hospitalized,total_test,daily_test
date,,,,,,,,,,,
2020-01-22,0,0,0,0,0,0,0,0,0,0,0
2020-01-23,0,0,0,0,0,0,0,0,0,0,0
2020-01-24,0,0,0,0,0,0,0,0,0,0,0
2020-01-25,0,0,0,0,0,0,0,0,0,0,0
2020-01-26,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2020-04-20,0,0,0,0,0,0,0,0,0,0,0
2020-04-21,0,0,0,0,0,0,0,0,0,0,0
2020-04-22,0,0,0,0,0,0,0,0,0,0,0
2020-04-23,0,0,0,0,0,0,0,0,0,0,0
2020-04-24,0,0,0,0,0,0,0,0,0,0,0

Filling the new dataframe with the avaiable data

In [12]:
day = []
for days in dataset.index:
    try:
        #from 2nd row
        usa_dataset.loc[days]["daily_cases"] = dataset.loc[days]["positiveIncrease"]
        usa_dataset.loc[days]["daily_dead"] = dataset.loc[days]["deathIncrease"]
        usa_dataset.loc[days]["daily_home_isolation"] = (dataset.loc[days]["positive"] - dataset.loc[days]["hospitalized"] - dataset.loc[days]["death"]) - (dataset.loc[days-dt.timedelta(days=1)]["positive"] - dataset.loc[days-dt.timedelta(days=1)]["hospitalized"] - dataset.loc[days-dt.timedelta(days=1)]["death"]) #Instead of positive should be actual cases
        usa_dataset.loc[days]["daily_hospitalized"] = dataset.loc[days]["hospitalized"] - dataset.loc[days-dt.timedelta(days=1)]["hospitalized"]
        usa_dataset.loc[days]["daily_test"] = dataset.loc[days]["total"] - dataset.loc[days-dt.timedelta(days=1)]["total"]
    except:
        #First row
        usa_dataset.loc[days]["daily_cases"] = dataset.loc[days]["positive"]
        usa_dataset.loc[days]["daily_dead"] = dataset.loc[days]["death"]
        usa_dataset.loc[days]["daily_home_isolation"] = (dataset.loc[days]["positive"] - dataset.loc[days]["hospitalized"] - dataset.loc[days]["death"]) #Instead of positive should be actual cases
        usa_dataset.loc[days]["daily_hospitalized"] = dataset.loc[days]["hospitalized"]
        usa_dataset.loc[days]["daily_test"] = dataset.loc[days]["total"]
    finally:
        #Single row
        usa_dataset.loc[days]["total_cases"] = dataset.loc[days]["positive"]
        usa_dataset.loc[days]["actual_cases"] = dataset.loc[days]["positive"] - dataset.loc[days]["recovered"] - dataset.loc[days]["death"]
        usa_dataset.loc[days]["total_dead"] = dataset.loc[days]["death"]
        usa_dataset.loc[days]["total_home_isolation"] = dataset.loc[days]["positive"]-dataset.loc[days]["hospitalized"] - dataset.loc[days]["death"] #Instead of positive should be actual cases
        usa_dataset.loc[days]["total_hospitalized"] = dataset.loc[days]["hospitalized"]
        usa_dataset.loc[days]["total_test"] = dataset.loc[days]["total"]


usa_dataset

,total_cases,daily_cases,actual_cases,total_dead,daily_dead,total_home_isolation,daily_home_isolation,total_hospitalized,daily_hospitalized,total_test,daily_test
date,,,,,,,,,,,
2020-01-22,1,1,1,0,0,1,1,0,0,1,1
2020-01-23,1,0,1,0,0,1,0,0,0,1,0
2020-01-24,1,0,1,0,0,1,0,0,0,1,0
2020-01-25,1,0,1,0,0,1,0,0,0,1,0
2020-01-26,1,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
2020-04-20,773020,23534,681261,37321,1528,652820,20008,82879,1998,4008084,130613
2020-04-21,800305,27285,702193,39995,2674,676018,23198,84292,1413,4159543,151459
2020-04-22,827963,27658,724316,42128,2133,700292,24274,85543,1251,4473386,313843
2020-04-23,859318,31355,751757,44014,1886,724196,23904,91108,5565,4664508,191122
2020-04-24,890816,31498,764072,45786,1772,751923,27727,93107,1999,4888198,223690

In [13]:
#get path for os
path = os.getcwd() + "/parsed_data/usa/"
path = path.replace("/",os.path.sep)
#save data as CSV 
usa_dataset.to_csv (path + "usa.csv", index = True, header=True)