Import Indonesia data

In [2]:
import pandas as pd
import glob
import os


path = os.getcwd() + "/Data/Indonesia/indonesia-coronavirus-cases/cases.csv"

columns = ["total_cases","daily_cases","actual_cases","total_healed","daily_healed","total_dead","daily_dead",
                  "total_test","daily_test"]

dataset = pd.read_csv(path, index_col = 0)
dataset = dataset.fillna(0)

In [3]:
dataset

,acc_tested,new_confirmed,acc_confirmed,acc_negative,being_checked,isolated,new_released,acc_released,new_deceased,acc_deceased,positive_rate,negative_rate,decease_rate,release_rate
date,,,,,,,,,,,,,,
2-Mar-20,339.0,2.0,2.0,335.0,2.0,2.0,0.0,0.0,0.0,0.0,0.59%,98.82%,0.00%,0.00%
3-Mar-20,341.0,0.0,2.0,337.0,2.0,2.0,0.0,0.0,0.0,0.0,0.59%,98.83%,0.00%,0.00%
4-Mar-20,372.0,0.0,2.0,356.0,14.0,2.0,0.0,0.0,0.0,0.0,0.54%,95.70%,0.00%,0.00%
5-Mar-20,388.0,0.0,2.0,371.0,15.0,2.0,0.0,0.0,0.0,0.0,0.52%,95.62%,0.00%,0.00%
6-Mar-20,450.0,2.0,4.0,422.0,24.0,4.0,0.0,0.0,0.0,0.0,0.89%,93.78%,0.00%,0.00%
7-Mar-20,454.0,0.0,4.0,422.0,28.0,4.0,0.0,0.0,0.0,0.0,0.88%,92.95%,0.00%,0.00%
8-Mar-20,483.0,2.0,6.0,445.0,32.0,6.0,0.0,0.0,0.0,0.0,1.24%,92.13%,0.00%,0.00%
9-Mar-20,543.0,13.0,19.0,487.0,37.0,19.0,0.0,0.0,0.0,0.0,3.50%,89.69%,0.00%,0.00%
10-Mar-20,694.0,8.0,27.0,648.0,19.0,27.0,0.0,0.0,0.0,0.0,3.89%,93.37%,0.00%,0.00%
11-Mar-20,793.0,7.0,34.0,744.0,15.0,30.0,2.0,2.0,2.0,2.0,4.29%,93.82%,5.88%,5.88%
12-Mar-20,862.0,0.0,34.0,811.0,17.0,27.0,1.0,3.0,2.0,4.0,3.94%,94.08%,11.76%,8.82%
13-Mar-20,1005.0,35.0,69.0,917.0,19.0,60.0,2.0,5.0,0.0,4.0,6.87%,91.24%,5.80%,7.25%
14-Mar-20,1105.0,27.0,96.0,1009.0,0.0,83.0,3.0,8.0,1.0,5.0,7.97%,91.31%,5.21%,8.33%
15-Mar-20,1193.0,21.0,117.0,1067.0,9.0,104.0,0.0,8.0,0.0,5.0,9.05%,89.44%,4.27%,6.84%
16-Mar-20,1230.0,17.0,134.0,1083.0,13.0,121.0,0.0,8.0,0.0,5.0,10.89%,88.05%,3.73%,5.97%
17-Mar-20,1255.0,38.0,172.0,1083.0,0.0,156.0,1.0,9.0,2.0,7.0,13.71%,86.29%,4.07%,5.23%
18-Mar-20,1592.0,55.0,227.0,1342.0,23.0,197.0,2.0,11.0,12.0,19.0,14.26%,84.30%,8.37%,4.85%
19-Mar-20,1651.0,82.0,309.0,1342.0,0.0,269.0,4.0,15.0,6.0,25.0,18.72%,81.28%,8.09%,4.85%
20-Mar-20,2028.0,60.0,369.0,1643.0,18.0,321.0,1.0,16.0,7.0,32.0,18.20%,81.02%,8.67%,4.34%
21-Mar-20,2365.0,81.0,450.0,1895.0,20.0,392.0,4.0,20.0,6.0,38.0,19.03%,80.13%,8.44%,4.44%
22-Mar-20,2409.0,64.0,514.0,1895.0,0.0,437.0,9.0,29.0,10.0,48.0,21.34%,78.66%,9.34%,5.64%
23-Mar-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0

Creating a new dataframe with our specific format

In [5]:
indonesia_dataset = pd.DataFrame(index = dataset.index , columns = columns) 
indonesia_dataset = indonesia_dataset.fillna(0)
indonesia_dataset

,total_cases,daily_cases,actual_cases,total_healed,daily_healed,total_dead,daily_dead,total_test,daily_test
date,,,,,,,,,
2-Mar-20,0,0,0,0,0,0,0,0,0
3-Mar-20,0,0,0,0,0,0,0,0,0
4-Mar-20,0,0,0,0,0,0,0,0,0
5-Mar-20,0,0,0,0,0,0,0,0,0
6-Mar-20,0,0,0,0,0,0,0,0,0
7-Mar-20,0,0,0,0,0,0,0,0,0
8-Mar-20,0,0,0,0,0,0,0,0,0
9-Mar-20,0,0,0,0,0,0,0,0,0
10-Mar-20,0,0,0,0,0,0,0,0,0
11-Mar-20,0,0,0,0,0,0,0,0,0
12-Mar-20,0,0,0,0,0,0,0,0,0
13-Mar-20,0,0,0,0,0,0,0,0,0
14-Mar-20,0,0,0,0,0,0,0,0,0
15-Mar-20,0,0,0,0,0,0,0,0,0
16-Mar-20,0,0,0,0,0,0,0,0,0
17-Mar-20,0,0,0,0,0,0,0,0,0
18-Mar-20,0,0,0,0,0,0,0,0,0
19-Mar-20,0,0,0,0,0,0,0,0,0
20-Mar-20,0,0,0,0,0,0,0,0,0
21-Mar-20,0,0,0,0,0,0,0,0,0
22-Mar-20,0,0,0,0,0,0,0,0,0
23-Mar-20,0,0,0,0,0,0,0,0,0

Filling the new dataframe with the avaiable data

In [25]:
from datetime import datetime, timedelta
day = []
for days in dataset.index:
    try:
        #from 2nd row ---- to subtract a day from the date we had to convert it to a date and then back to a string
        yesterday = (datetime.strptime(days,"%d-%b-%y")-timedelta(days=1)).strftime("%-d-%b-%y")
        indonesia_dataset.loc[days]["daily_test"] = dataset.loc[days]["acc_tested"] - dataset.loc[yesterday]["acc_tested"]
    except:
        #First row
        indonesia_dataset.loc[days]["daily_test"] = dataset.loc[days]["acc_tested"]
    finally:
        #Single row
        indonesia_dataset.loc[days]["total_cases"] = dataset.loc[days]["acc_confirmed"]
        indonesia_dataset.loc[days]["daily_cases"] = dataset.loc[days]["new_confirmed"]
        indonesia_dataset.loc[days]["actual_cases"] = dataset.loc[days]["isolated"]
        indonesia_dataset.loc[days]["total_healed"] = dataset.loc[days]["acc_released"]
        indonesia_dataset.loc[days]["daily_healed"] = dataset.loc[days]["new_released"]
        indonesia_dataset.loc[days]["total_dead"] = dataset.loc[days]["acc_deceased"]
        indonesia_dataset.loc[days]["daily_dead"] = dataset.loc[days]["new_deceased"]
        indonesia_dataset.loc[days]["total_test"] = dataset.loc[days]["acc_tested"]
        

indonesia_dataset

,total_cases,daily_cases,actual_cases,total_healed,daily_healed,total_dead,daily_dead,total_test,daily_test
date,,,,,,,,,
2-Mar-20,2,2,2,0,0,0,0,339,339
3-Mar-20,2,0,2,0,0,0,0,341,2
4-Mar-20,2,0,2,0,0,0,0,372,31
5-Mar-20,2,0,2,0,0,0,0,388,16
6-Mar-20,4,2,4,0,0,0,0,450,62
7-Mar-20,4,0,4,0,0,0,0,454,4
8-Mar-20,6,2,6,0,0,0,0,483,29
9-Mar-20,19,13,19,0,0,0,0,543,60
10-Mar-20,27,8,27,0,0,0,0,694,151
11-Mar-20,34,7,30,2,2,2,2,793,99
12-Mar-20,34,0,27,3,1,4,2,862,69
13-Mar-20,69,35,60,5,2,4,0,1005,143
14-Mar-20,96,27,83,8,3,5,1,1105,100
15-Mar-20,117,21,104,8,0,5,0,1193,88
16-Mar-20,134,17,121,8,0,5,0,1230,37
17-Mar-20,172,38,156,9,1,7,2,1255,25
18-Mar-20,227,55,197,11,2,19,12,1592,337
19-Mar-20,309,82,269,15,4,25,6,1651,59
20-Mar-20,369,60,321,16,1,32,7,2028,377
21-Mar-20,450,81,392,20,4,38,6,2365,337
22-Mar-20,514,64,437,29,9,48,10,2409,44
23-Mar-20,0,0,0,0,0,0,0,0,-2409